// export About from './About/About';
export App from './App/App';
// export ChatFeathers from './ChatFeathers/ChatFeathers';
export Home from './Home/Home';
// export Login from './Login/Login';
// export LoginSuccess from './LoginSuccess/LoginSuccess';
export NotFound from './NotFound/NotFound';
export Catalog from './Catalog/Catalog';
export ClassCatalog from './ClassCatalog/Catalog';
// export Register from './Register/Register';
